[package]
name = "euler"
version = "0.1.0"
authors = ["anthony"]
edition = "2018"

[lib]
name = "euler_tools"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rayon = "1.5"
num_cpus = "1.13.1"